// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Db_First_Using_EF_Core_Power_Tools.Data.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Db_First_Using_EF_Core_Power_Tools.Data.Models
{
    public partial interface INorthwindDbContextProcedures
    {
        Task<int> DeleteCategoryByCategoryIDAsync(int? categoryID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteEmployeeByIDAsync(int? employeeID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
